### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Sokolcav** [Alvin-22/Eagle-Eyes#1]
Can you upload a tutorial how to setup this in kali linux

**Comment by afahitech** [comment]
Please try it in  Ubuntu

![Screenshot from 2021-01-26 23-41-03](https://user-images.githubusercontent.com/57868100/105882579-03993100-6030-11eb-8279-5109fe92928c.png)

**Comment by Alvin-22** [comment]
> Can you upload a tutorial how to setup this in kali linux

It only works on Windows

**Comment by Alvin-22** [comment]
> Please try it on Ubuntu
> 
> ![Screenshot from 2021-01-26 23-41-03](https://user-images.githubusercontent.com/57868100/105882579-03993100-6030-11eb-8279-5109fe92928c.png)

Not sure what this is
